### ISSUE TITLE
Secret rolls for the keeper

### ISSUE THREAD

**Issue by notArtist** [russellaugust/call-of-cthulhu-dicebot#13]
New syntax: .s for secret or screen

Uses the same roll method as .r, but DMs the user who calls for it and sends a different message to the channel, like: 

> [USER] rolls #[NOTE] behind the keeper's screen!

Could also pair with a voice result of 'Hmm...' 'Interesting!' or 'Ooh!'  Or maybe that sound of sucking in air through your teeth.

**Comment by russellaugust** [comment]
i like this.

the only thing is that it overlaps with other existing rolls.  so maybe...

```
.sr - secret roll
.sb - secret bonus
.sp - secret penalty
.ri - secret improve
```

we could also use flags.  

so then something like:

```
.r 45 -s # secret roll!
```

**Comment by russellaugust** [comment]
this has been implemented through slash commands and ephemeral messages.
