### ISSUE TITLE
Add roll syntax for advantage / disadvantage

### ISSUE THREAD

**Issue by russellaugust** [russellaugust/call-of-cthulhu-dicebot#8]
Add some rolling syntax to allow for a quick advantage (roll twice, take the best) and disadvantage (roll twice, take the worst). 

Possible syntax:

`!r 45+`
`!r 45-`

`!r+ 45`
`!r- 45`

Is there any situation where you'd need to roll anything other than a stat or `d100`?  If so it could be the same syntax. 

`!r+ 1d6+5`

I think I like the +/- at the beginning better. It implies it's a roll at advantage. Adding it to the end also runs the risk of it getting lumped into a mathematical roll like `1d4+8`.

**Comment by russellaugust** [comment]
`!r +45` could also work.  This might be easier to implement.  Need to check to see how hard it is to implement `!r+ 50`

**Comment by notArtist** [comment]
I suggest .b or .bonus as an easier-to-understand call for less savvy users. .p or .penalty to match? 

The catch, however, is that there are times when a roll can be made with 2 bonus or penalty dice.  Could it be done with one extra roll for each + or - in the command?
